### ISSUE TITLE
Compatibility with OxidizeLIb

### ISSUE THREAD

**Issue by queenielawrens** [finallion/Overgrown_Blocks_-FABRIC-#1]
Probably not of incredible importance, but your mod conflicts with [OxidizeLib by Shnupbups](https://github.com/Shnupbups/oxidizelib) (Found in [RedstoneBits](https://www.curseforge.com/minecraft/mc-mods/redstone-bits) by the same author). 

Versions:
Overgrown Blocks: 1.2
OxidizeLib: 1.0.0
Fabric API: 0.37.0
Minecraft: 1.17.1

Crash Report:
```
[01:36:48] [main/WARN]: @Redirect conflict. Skipping oxidizelib.mixins.json:AxeItemMixin->@Redirect::redirectGetUnwaxedState(Ljava/lang/Object;Lnet/minecraft/class_1838;)Ljava/util/Optional; with priority 1000, already redirected by mossywood.mixins.json:AxeItemMixin->@Redirect::redirectGetUnwaxedState(Ljava/lang/Object;Lnet/minecraft/class_1838;)Ljava/util/Optional; with priority 1000
Failed to start Minecraft:
java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
Caused by: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:236)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)
	... 8 more
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234)
	... 10 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:208)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:178)
	at org.spongepowered.asm.mixin.transformer.FabricMixinTransformerProxy.transformClassBytes(FabricMixinTransformerProxy.java:23)
	at net.fabricmc.loader.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:162)
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:154)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:519)
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1010)
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150)
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:170)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:519)
	at com.hugman.dawn.api.creator.bundle.block.LogsBundle.<init>(LogsBundle.java:48)
	at com.hugman.dawn.api.creator.bundle.block.WoodBundle.<init>(WoodBundle.java:20)
	at com.hugman.dawn.api.creator.bundle.block.WoodBundle$Builder.build(WoodBundle.java:101)
	at com.hugman.promenade.init.PromenadeBlocks.<clinit>(PromenadeBlocks.java:104)
	at com.hugman.promenade.init.world.PromenadeConfiguredFeatures$States.<clinit>(PromenadeConfiguredFeatures.java:216)
	at com.hugman.promenade.init.world.PromenadeConfiguredFeatures.<clinit>(PromenadeConfiguredFeatures.java:44)
	at net.minecraft.class_3864.handler$zga000$WE_addMineables(class_3864.java:597)
	at net.minecraft.class_3864.method_17005(class_3864.java:92)
	at net.minecraft.class_5478.method_31066(class_5478.java:712)
	at net.minecraft.class_5478.method_30706(class_5478.java:744)
	at net.minecraft.class_5504.<clinit>(class_5504.java:17)
	at net.minecraft.class_5458.method_30567(class_5458.java:52)
	at net.minecraft.class_5458.method_30566(class_5458.java:75)
	at java.base/java.util.LinkedHashMap.forEach(LinkedHashMap.java:723)
	at net.minecraft.class_5458.<clinit>(class_5458.java:74)
	at net.minecraft.class_2378.<clinit>(class_2378.java:266)
	at net.minecraft.class_2966.method_12851(class_2966.java:44)
	at net.minecraft.client.main.Main.main(Main.java:139)
	... 15 more
Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Redirector redirectGetUnwaxedState(Ljava/lang/Object;Lnet/minecraft/class_1838;)Ljava/util/Optional; in oxidizelib.mixins.json:AxeItemMixin failed injection check, (0/1) succeeded. Scanned 1 target(s). Using refmap oxidizelib-refmap.json
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.postInject(InjectionInfo.java:408)
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1291)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1042)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:395)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:320)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:345)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:569)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:351)
	... 44 more
Exiting with -1
Process exited with code -1.

```

**Comment by finallion** [comment]
Thanks for opening the issue. Using the oxidizing mechanic requires to override a specific method. If two mods override the same, it crashes. I'll look into the OxidizeLib and maybe integrate it so there should be no more compat issues (at least with mods using the library.)

**Comment by finallion** [comment]
I implemented OxidizeLib. This should fix the compat issue.
